credentials

diff --git a/deploy/Jenkinsfile b/deploy/Jenkinsfile
--- a/deploy/Jenkinsfile
+++ b/deploy/Jenkinsfile
@@ -35,6 +35,27 @@ pipeline {
                     aws cloudfront create-invalidation \
                         --distribution-id ${env.CLOUDFRONT_ID} \
                         --paths "/*"
+
+                    CLOUDFRONT_INVALIDATION_ID=aws cloudfront create-invalidation --distribution-id E165NDOJ0Q86CD --paths /* | jq ".Invalidation.Id"
+
+                    attempt_counter=0
+                    max_attempts=5
+
+                    waitForCompleted () {
+                        while IFS=read -r line
+                        do
+                            CLOUDFRONT_INVALIDATION_STATUS=$(aws cloudfront get-invalidation --id I29G7388Z3WN7F --distribution-id E165NDOJ0Q86CD | jq ".Invalidation.Status")
+
+                            if [[ CLOUDFRONT_INVALIDATION_STATUS -eq "Completed" ]]; then
+                                break
+                            fi
+
+                            echo "$CLOUDFRONT_INVALIDATION_STATUS"
+                            echo "Retry"
+                        done
+                    } <<(timeout 1s cat /dev/urandom && exit 1)
+
+                    waitForCompleted
                 """
             }
         }
